// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: robotserver/robotserver_fight.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace RobotserverFight {

  /// <summary>Holder for reflection information generated from robotserver/robotserver_fight.proto</summary>
  public static partial class RobotserverFightReflection {

    #region Descriptor
    /// <summary>File descriptor for robotserver/robotserver_fight.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static RobotserverFightReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiNyb2JvdHNlcnZlci9yb2JvdHNlcnZlcl9maWdodC5wcm90bxIRcm9ib3Rz",
            "ZXJ2ZXJfZmlnaHQaE2NvbW1vbi9jb21tb24ucHJvdG8iYAoNVXBQbGF5Q2Fy",
            "ZFJlcRIPCgdyb29tX2lkGAEgASgDEhEKCXBsYXllcl9pZBgCIAEoAxIPCgdj",
            "aGFyX2lkGAMgASgDEhoKBENhcmQYBCABKAsyDC5jb21tb24uQ2FyZCJVCg1V",
            "cFBsYXlDYXJkUmVzEg8KB3Jvb21faWQYASABKAMSEQoJcGxheWVyX2lkGAIg",
            "ASgDEg8KB2NoYXJfaWQYAyABKAMSDwoHY2hhcl9IcBgEIAEoAyoeCgRtYWlu",
            "EhYKEXJvYm90c2VydmVyX2ZpZ2h0ENkEKjMKA3N1YhIVChFDTURfVXBQbGF5",
            "Q2FyZFJlcRABEhUKEUNNRF9VcFBsYXlDYXJkUmVzEAI="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Common.CommonReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::RobotserverFight.main), typeof(global::RobotserverFight.sub), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::RobotserverFight.UpPlayCardReq), global::RobotserverFight.UpPlayCardReq.Parser, new[]{ "RoomId", "PlayerId", "CharId", "Card" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::RobotserverFight.UpPlayCardRes), global::RobotserverFight.UpPlayCardRes.Parser, new[]{ "RoomId", "PlayerId", "CharId", "CharHp" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  ///协议主码 本服独有协议 占用 101-654 公共占用1-50 游戏公共占用50-100
  /// </summary>
  public enum main {
    [pbr::OriginalName("robotserver_fight")] RobotserverFight = 601,
  }

  /// <summary>
  ///协议子码 req res 占用1-80  通知占用80-100
  /// </summary>
  public enum sub {
    [pbr::OriginalName("CMD_UpPlayCardReq")] CmdUpPlayCardReq = 1,
    [pbr::OriginalName("CMD_UpPlayCardRes")] CmdUpPlayCardRes = 2,
  }

  #endregion

  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class UpPlayCardReq : pb::IMessage<UpPlayCardReq>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<UpPlayCardReq> _parser = new pb::MessageParser<UpPlayCardReq>(() => new UpPlayCardReq());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<UpPlayCardReq> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::RobotserverFight.RobotserverFightReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpPlayCardReq() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpPlayCardReq(UpPlayCardReq other) : this() {
      _hasBits0 = other._hasBits0;
      roomId_ = other.roomId_;
      playerId_ = other.playerId_;
      charId_ = other.charId_;
      card_ = other.card_ != null ? other.card_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpPlayCardReq Clone() {
      return new UpPlayCardReq(this);
    }

    /// <summary>Field number for the "room_id" field.</summary>
    public const int RoomIdFieldNumber = 1;
    private readonly static long RoomIdDefaultValue = 0L;

    private long roomId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long RoomId {
      get { if ((_hasBits0 & 1) != 0) { return roomId_; } else { return RoomIdDefaultValue; } }
      set {
        _hasBits0 |= 1;
        roomId_ = value;
      }
    }
    /// <summary>Gets whether the "room_id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasRoomId {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "room_id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearRoomId() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "player_id" field.</summary>
    public const int PlayerIdFieldNumber = 2;
    private readonly static long PlayerIdDefaultValue = 0L;

    private long playerId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long PlayerId {
      get { if ((_hasBits0 & 2) != 0) { return playerId_; } else { return PlayerIdDefaultValue; } }
      set {
        _hasBits0 |= 2;
        playerId_ = value;
      }
    }
    /// <summary>Gets whether the "player_id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasPlayerId {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "player_id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPlayerId() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "char_id" field.</summary>
    public const int CharIdFieldNumber = 3;
    private readonly static long CharIdDefaultValue = 0L;

    private long charId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long CharId {
      get { if ((_hasBits0 & 4) != 0) { return charId_; } else { return CharIdDefaultValue; } }
      set {
        _hasBits0 |= 4;
        charId_ = value;
      }
    }
    /// <summary>Gets whether the "char_id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasCharId {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "char_id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearCharId() {
      _hasBits0 &= ~4;
    }

    /// <summary>Field number for the "Card" field.</summary>
    public const int CardFieldNumber = 4;
    private global::Common.Card card_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Common.Card Card {
      get { return card_; }
      set {
        card_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as UpPlayCardReq);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(UpPlayCardReq other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (RoomId != other.RoomId) return false;
      if (PlayerId != other.PlayerId) return false;
      if (CharId != other.CharId) return false;
      if (!object.Equals(Card, other.Card)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasRoomId) hash ^= RoomId.GetHashCode();
      if (HasPlayerId) hash ^= PlayerId.GetHashCode();
      if (HasCharId) hash ^= CharId.GetHashCode();
      if (card_ != null) hash ^= Card.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasRoomId) {
        output.WriteRawTag(8);
        output.WriteInt64(RoomId);
      }
      if (HasPlayerId) {
        output.WriteRawTag(16);
        output.WriteInt64(PlayerId);
      }
      if (HasCharId) {
        output.WriteRawTag(24);
        output.WriteInt64(CharId);
      }
      if (card_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Card);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasRoomId) {
        output.WriteRawTag(8);
        output.WriteInt64(RoomId);
      }
      if (HasPlayerId) {
        output.WriteRawTag(16);
        output.WriteInt64(PlayerId);
      }
      if (HasCharId) {
        output.WriteRawTag(24);
        output.WriteInt64(CharId);
      }
      if (card_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Card);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasRoomId) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(RoomId);
      }
      if (HasPlayerId) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(PlayerId);
      }
      if (HasCharId) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(CharId);
      }
      if (card_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Card);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(UpPlayCardReq other) {
      if (other == null) {
        return;
      }
      if (other.HasRoomId) {
        RoomId = other.RoomId;
      }
      if (other.HasPlayerId) {
        PlayerId = other.PlayerId;
      }
      if (other.HasCharId) {
        CharId = other.CharId;
      }
      if (other.card_ != null) {
        if (card_ == null) {
          Card = new global::Common.Card();
        }
        Card.MergeFrom(other.Card);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            RoomId = input.ReadInt64();
            break;
          }
          case 16: {
            PlayerId = input.ReadInt64();
            break;
          }
          case 24: {
            CharId = input.ReadInt64();
            break;
          }
          case 34: {
            if (card_ == null) {
              Card = new global::Common.Card();
            }
            input.ReadMessage(Card);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            RoomId = input.ReadInt64();
            break;
          }
          case 16: {
            PlayerId = input.ReadInt64();
            break;
          }
          case 24: {
            CharId = input.ReadInt64();
            break;
          }
          case 34: {
            if (card_ == null) {
              Card = new global::Common.Card();
            }
            input.ReadMessage(Card);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class UpPlayCardRes : pb::IMessage<UpPlayCardRes>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<UpPlayCardRes> _parser = new pb::MessageParser<UpPlayCardRes>(() => new UpPlayCardRes());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<UpPlayCardRes> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::RobotserverFight.RobotserverFightReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpPlayCardRes() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpPlayCardRes(UpPlayCardRes other) : this() {
      _hasBits0 = other._hasBits0;
      roomId_ = other.roomId_;
      playerId_ = other.playerId_;
      charId_ = other.charId_;
      charHp_ = other.charHp_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpPlayCardRes Clone() {
      return new UpPlayCardRes(this);
    }

    /// <summary>Field number for the "room_id" field.</summary>
    public const int RoomIdFieldNumber = 1;
    private readonly static long RoomIdDefaultValue = 0L;

    private long roomId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long RoomId {
      get { if ((_hasBits0 & 1) != 0) { return roomId_; } else { return RoomIdDefaultValue; } }
      set {
        _hasBits0 |= 1;
        roomId_ = value;
      }
    }
    /// <summary>Gets whether the "room_id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasRoomId {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "room_id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearRoomId() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "player_id" field.</summary>
    public const int PlayerIdFieldNumber = 2;
    private readonly static long PlayerIdDefaultValue = 0L;

    private long playerId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long PlayerId {
      get { if ((_hasBits0 & 2) != 0) { return playerId_; } else { return PlayerIdDefaultValue; } }
      set {
        _hasBits0 |= 2;
        playerId_ = value;
      }
    }
    /// <summary>Gets whether the "player_id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasPlayerId {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "player_id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPlayerId() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "char_id" field.</summary>
    public const int CharIdFieldNumber = 3;
    private readonly static long CharIdDefaultValue = 0L;

    private long charId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long CharId {
      get { if ((_hasBits0 & 4) != 0) { return charId_; } else { return CharIdDefaultValue; } }
      set {
        _hasBits0 |= 4;
        charId_ = value;
      }
    }
    /// <summary>Gets whether the "char_id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasCharId {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "char_id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearCharId() {
      _hasBits0 &= ~4;
    }

    /// <summary>Field number for the "char_Hp" field.</summary>
    public const int CharHpFieldNumber = 4;
    private readonly static long CharHpDefaultValue = 0L;

    private long charHp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long CharHp {
      get { if ((_hasBits0 & 8) != 0) { return charHp_; } else { return CharHpDefaultValue; } }
      set {
        _hasBits0 |= 8;
        charHp_ = value;
      }
    }
    /// <summary>Gets whether the "char_Hp" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasCharHp {
      get { return (_hasBits0 & 8) != 0; }
    }
    /// <summary>Clears the value of the "char_Hp" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearCharHp() {
      _hasBits0 &= ~8;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as UpPlayCardRes);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(UpPlayCardRes other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (RoomId != other.RoomId) return false;
      if (PlayerId != other.PlayerId) return false;
      if (CharId != other.CharId) return false;
      if (CharHp != other.CharHp) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasRoomId) hash ^= RoomId.GetHashCode();
      if (HasPlayerId) hash ^= PlayerId.GetHashCode();
      if (HasCharId) hash ^= CharId.GetHashCode();
      if (HasCharHp) hash ^= CharHp.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasRoomId) {
        output.WriteRawTag(8);
        output.WriteInt64(RoomId);
      }
      if (HasPlayerId) {
        output.WriteRawTag(16);
        output.WriteInt64(PlayerId);
      }
      if (HasCharId) {
        output.WriteRawTag(24);
        output.WriteInt64(CharId);
      }
      if (HasCharHp) {
        output.WriteRawTag(32);
        output.WriteInt64(CharHp);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasRoomId) {
        output.WriteRawTag(8);
        output.WriteInt64(RoomId);
      }
      if (HasPlayerId) {
        output.WriteRawTag(16);
        output.WriteInt64(PlayerId);
      }
      if (HasCharId) {
        output.WriteRawTag(24);
        output.WriteInt64(CharId);
      }
      if (HasCharHp) {
        output.WriteRawTag(32);
        output.WriteInt64(CharHp);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasRoomId) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(RoomId);
      }
      if (HasPlayerId) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(PlayerId);
      }
      if (HasCharId) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(CharId);
      }
      if (HasCharHp) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(CharHp);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(UpPlayCardRes other) {
      if (other == null) {
        return;
      }
      if (other.HasRoomId) {
        RoomId = other.RoomId;
      }
      if (other.HasPlayerId) {
        PlayerId = other.PlayerId;
      }
      if (other.HasCharId) {
        CharId = other.CharId;
      }
      if (other.HasCharHp) {
        CharHp = other.CharHp;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            RoomId = input.ReadInt64();
            break;
          }
          case 16: {
            PlayerId = input.ReadInt64();
            break;
          }
          case 24: {
            CharId = input.ReadInt64();
            break;
          }
          case 32: {
            CharHp = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            RoomId = input.ReadInt64();
            break;
          }
          case 16: {
            PlayerId = input.ReadInt64();
            break;
          }
          case 24: {
            CharId = input.ReadInt64();
            break;
          }
          case 32: {
            CharHp = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
