import "common/common.proto";

package hallserver_map;

//协议主码 本服独有协议 占用 101-654 公共占用1-50 游戏公共占用50-100
enum main {
	hallserver_map = 105;
}
//协议子码 req res 占用1-80  通知占用80-100
enum sub {
	CMD_ToEnterMapReq  = 1;
	CMD_ToEnterMapRes  = 2;
	CMD_GetOtherPlayMapSignReq = 3;
	CMD_GetOtherPlayMapSignRes = 4;
}

//大厅登录进入地图场景
message ToEnterMapReq{
	optional int64 player_id = 1;           //玩家ID
	repeated common.Item item_list = 2; 
}

//大厅登录进入地图场景
message ToEnterMapRes{
	optional int64 map_id = 1;           //地图ID
}

message GetOtherPlayMapSignReq{
	optional int64 player_id = 1;
}

message GetOtherPlayMapSignRes{
	optional int64 map_id = 1;
}