package mapserver_other;

//协议主码 本服独有协议 占用 101-654 公共占用1-50 游戏公共占用50-100
enum main {
	mapserver_other = 205;
}
//协议子码 req res 占用1-80  通知占用80-100
enum sub {
	CMD_SelectOthRegionReq = 1;
	CMD_SelectOthRegionRes = 2;
	CMD_OtherPlayerMapNotice  = 80;
}

message OneRegion{
	optional int64 player_id = 1;
	optional int64 region_id = 2;
	optional int32 is_open = 3;
	optional int32 is_jump = 4;
	optional int32 clear_star = 5;
	optional int32 is_building = 6;
	optional int64 build_id = 7; 
}


//发送区域选择信息
message SelectOthRegionReq{
	optional int64 player_id = 1;           //玩家ID
	optional int64 region_id = 2;
}

//区域信息选择通知
message SelectOthRegionRes{
	optional OneRegion region = 1;    
}

message OtherPlayerMapNotice{
	optional int64 player_id = 1;
	optional int64 map_id = 2;
	optional string map_name = 3;
	repeated int32  region_ids = 4;
	optional int32 is_open = 5;
	optional int32 clear_star = 6;
	optional int32 is_building = 7;
	optional int64 build_id = 8;
}